modules/staff/controllers/ParentsController.php
<?php

namespace app\modules\staff\controllers;

use Yii;
use app\models\Parents;
use app\models\ParentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\ParentStudent;
use app\models\Student;
use app\models\PasswordResetForm;
use app\models\GeneralSettings;

/**
 * ParentsController implements the CRUD actions for Parents model.
 */
class ParentsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Parents models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        $searchModel = new ParentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Parents model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Parents model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        $model = new Parents();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) 
        {   
            $passwordString = GeneralSettings::getRandomString();
            $model->password = hash('sha256', $passwordString);
            $model->created_on = date('Y-m-d');

            if($model->save(false))
            {
                Yii::$app->mailer
                ->compose('new-parent-credentials', ['parent' => $model, 'password' => $passwordString])
                ->setFrom('jiddaknight@yahoo.com')
                ->setTo($model->email)        
                ->setSubject('RKIS Parent Portal Profile')
                ->send();
               return $this->redirect(['view', 'id' => $model->id]); 
            }
            
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Parents model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout = '@app/views/layouts/staffLayout.php';
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Parents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionLinkWard($id)
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        $model = new ParentStudent();

        $students = Student::find()->orderBy('first_name')->all();
    	$studentList = [];

    	foreach($students as $student)
    	{
    		$studentList[$student->id] = $student->getFullName() . " " . "({$student->getClassName()})";
        }
        
        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $model->creation_date = date('Y-m-d');
            if($model->save(false)) 
                return $this->redirect(['view', 'id' => $id]);
        }

        return $this->render('_link_ward_form', 
            [
                'model' => $model, 
                'parent' => $this->findModel($id),
                'studentList' => $studentList
            ]);
    }

    public function actionUnlinkWard($pid, $sid)
    {
        $model = ParentStudent::findOne(['parent_id' => $pid, 'student_id' => $sid])->delete();
        return $this->redirect(['view', 'id' => $pid]);
    }

    public function actionResetPassword($id)
    {
        $this->layout = '@app/views/layouts/staffLayout.php';
        $parent = Parents::findOne(['id' => $id]);
        

        if(Yii::$app->request->post())
        {
            $passwordString = GeneralSettings::getRandomString();
            $hash = hash('sha256', $passwordString);
            $parent->password = $hash;
           
            if($parent->save(false))
            {
                Yii::$app->session->setFlash('success', "Password reset successful!");

                Yii::$app->mailer
                ->compose('password-reset-notification', ['parent' => $parent, 'password' => $passwordString])
                ->setFrom('info@royalkiddiesschool.com')
                ->setTo($parent->email)        
                ->setSubject('ROKIS Parent Portal Password Reset')
                ->send();

            }

        }
        return $this->render('reset-user-password', ['user' => $parent]);
    }

    /**
     * Finds the Parents model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Parents the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Parents::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/staff/controllers/StudentController.php
<?php

namespace app\modules\staff\controllers;

use Yii;
use app\models\Student;
use app\models\StudentSearch;
use app\models\SchoolClass;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use app\models\Lgas;

/**
 * StudentController implements the CRUD actions for Student model.
 */
class StudentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Student models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        $searchModel = new StudentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Student model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Student model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = '@app/views/layouts/staffLayout.php';

        $model = new Student();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) 
        {
            $imageName = $model->first_name .'_' .rand(0,99999);
            $model->picture = UploadedFile::getInstance($model, 'picture');

            if(!empty($model->picture))
            {
                $model->picture->saveAs('images/student_pix/' . $imageName  . '.' . $model->picture->extension);
                $model->picture = '/images/student_pix/' . $imageName  . '.' . $model->picture->extension; 
            }
            
            $model->status = 'active';
            $model->created_on = date('Y-m-d');

            if($model->save(false)) return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Student model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout = '@app/views/layouts/staffLayout.php';
        
        $model = $this->findModel($id);
        $currentImage = $model->picture;

        $lgas = empty($model->state_of_origin) ? [] : ArrayHelper::map(Lgas::find()->where(['state_id' => $model->state_of_origin])->all(), 'id', 'lga_name');

        if ($model->load(Yii::$app->request->post()) && $model->validate()) 
        {
            $imageName = $model->first_name .'_' .rand(0,99999);
            $model->picture = UploadedFile::getInstance($model, 'picture');

            if(isset($model->picture->extension))
            {
                $model->picture->saveAs('images/student_pix/' . $imageName  . '.' . $model->picture->extension);
                $model->picture = '/images/student_pix/' . $imageName  . '.' . $model->picture->extension; 
            }

            else $model->picture = $currentImage;

            if($model->save(false)) return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'lgas' => $lgas
        ]);
    }

    /**
     * Deletes an existing Student model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Student model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Student the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Student::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionAjaxGetClass($studentId)
    {
        $currentClass = Student::findOne($studentId)->current_class;
        
        $class = SchoolClass::findOne($currentClass);

        return $this->asJson([
            'class_id' => $class->id,
            'class_name' => $class->class_name,
            'class_division' => $class->class_division
        ]);
    }

    
}

modules/staff/views/parents/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Parents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="w3-col">

    <?php $form = ActiveForm::begin([
        'id' => 'parent-creation-form',
        'options' => [
            'class' => 'w3-padding w3-border w3-light-grey',
            'enctype' => 'multipart/form-data',
            'autocomplete' => 'off'
        ]
    ]); ?>

    <div class="w3-row-padding">
        <div class="w3-third">
           <?= $form->field($model, 'first_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?> 
        </div>

        <div class="w3-third">
            <?= $form->field($model, 'middle_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>

        <div class="w3-third">
            <?= $form->field($model, 'last_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>
    </div>

    <fieldset class="w3-margin-top">
        <legend>Home Contact Information</legend>
        <div class="w3-row-padding">
            

                <div class="w3-quarter">
                    <?= $form->field($model, 'phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-quarter">
                    <?= $form->field($model, 'phone2')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-quarter">
                    <?= $form->field($model, 'residence_phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-quarter">
                    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-col">
                    <?= $form->field($model, 'address')->textarea(['rows' => 3, 'class' => 'w3-input w3-border']) ?>
                </div>
            
        </div>
    </fieldset>

    <fieldset class="w3-margin-top">
        <legend>Office Contact Information</legend>

        <div class="w3-row-padding">
            
            <div class="w3-half">
                <?= $form->field($model, 'employer')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
            </div>

            <div class="w3-half">
                <?= $form->field($model, 'office_phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
            </div>
            
            <div class="w3-col">
                <?= $form->field($model, 'work_address')->textarea(['rows' => 3, 'class' => 'w3-input w3-border']) ?>
            </div>

            <div class="w3-col">
                <?= $form->field($model, 'mailing_address')->textarea(['rows' => 3, 'class' => 'w3-input w3-border']) ?>
            </div>
            
        </div>
    </fieldset>
       

    <div class="w3-row-padding w3-margin-top w3-margin-bottom">
        <div class="w3-third">
            <?= Html::submitButton('Save', ['class' => 'w3-btn w3-green']) ?>
        </div>        
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/staff/views/parents/_link_ward_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Parents;
use app\models\Student;
use yii\web\View;
use kartik\select2\Select2;

$this->title = "Parents &amp; Wards";
$this->params['breadcrumbs'][] = ['label' => 'Manage Parents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $parent->getFullName(), 'url' => ['view', 'id' => $parent->id]];
$this->params['breadcrumbs'][] = 'Link Parent to Ward';
?>

<div class="w3-container w3-padding">
	
	<div class="w3-cell-row">
		<div class="w3-container w3-cell"></div>
		<div class="w3-container w3-cell">
			<h1><?= $this->title ?></h1>
			<?php $form = ActiveForm::begin([
		        'id' => 'parent-ward-form',
		        'options' => [
		            'class' => 'w3-border w3-light-grey',
		            'enctype' => 'multipart/form-data',
		            'autocomplete' => 'off'
		        ]
		    ]); ?>

		    <div class="w3-panel">
			    <h3 class="w3-blue w3-padding w3-margin-bottom">Link Parent to Ward</h3>
			    <div class="w3-row-padding">
			    	<div class="w3-third">
			    		<p>
			    			<label class="w3-label">Parent Name:</label>
			    			<h5><?= $parent->getFullName(); ?></h5>
			    		</p>
			    		<?= $form->field($model, 'parent_id')->hiddenInput([
			    			'value' => $parent->id
			    		]
			                )->label(false) ?>
			    	</div>

			    	<div class="w3-third">
						<?= 
							$form->field($model, 'student_id')->widget(Select2::classname(), [
								'data' => $studentList,                    
								'options' => ['placeholder' => 'Select student ...']								      
							])->label('Student');
						?>
			    	</div>

			    	<div class="w3-third">		    		
			    		<?= $form->field($model, 'relationship')->textInput(['class' => 'w3-input w3-border']) ?>
			    	</div>
			    </div>

		    	<div class="w3-row-padding">
		        <div class="w3-third">
		            <?= Html::submitButton('Save', ['class' => 'w3-btn w3-green']) ?>
		        </div>        
		    	</div>
		    </div>

		    <?php ActiveForm::end(); ?>
		</div>
		<div class="w3-container w3-cell"></div>
	</div>
</div>

modules/staff/views/parents/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ParentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="parents-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'middle_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'phone2') ?>

    <?php // echo $form->field($model, 'residence_phone') ?>

    <?php // echo $form->field($model, 'employer') ?>

    <?php // echo $form->field($model, 'office_phone') ?>

    <?php // echo $form->field($model, 'work_address') ?>

    <?php // echo $form->field($model, 'mailing_address') ?>

    <?php // echo $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'last_login') ?>

    <?php // echo $form->field($model, 'created_on') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/staff/views/parents/_update_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Parents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="w3-col">

    <?php $form = ActiveForm::begin([
        'id' => 'parent-creation-form',
        'options' => [
            'class' => 'w3-border w3-padding w3-light-grey',
            'enctype' => 'multipart/form-data',
            'autocomplete' => 'off'
        ]
    ]); ?>

    <div class="w3-row-padding">
        <div class="w3-third">
           <?= $form->field($model, 'first_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?> 
        </div>

        <div class="w3-third">
            <?= $form->field($model, 'middle_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>

        <div class="w3-third">
            <?= $form->field($model, 'last_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>
    </div>

    <fieldset class="w3-margin-top">
        <legend>Home Contact Information</legend>
        <div class="w3-row-padding">
            

                <div class="w3-quarter">
                    <?= $form->field($model, 'phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-quarter">
                    <?= $form->field($model, 'phone2')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-quarter">
                    <?= $form->field($model, 'residence_phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-quarter">
                    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
                </div>

                <div class="w3-col">
                    <?= $form->field($model, 'address')->textarea(['rows' => 3, 'class' => 'w3-input w3-border']) ?>
                </div>
            
        </div>
    </fieldset>

    <fieldset class="w3-margin-top">
        <legend>Office Contact Information</legend>

        <div class="w3-row-padding">
            
            <div class="w3-half">
                <?= $form->field($model, 'employer')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
            </div>

            <div class="w3-half">
                <?= $form->field($model, 'office_phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
            </div>
            
            <div class="w3-col">
                <?= $form->field($model, 'work_address')->textarea(['rows' => 3, 'class' => 'w3-input w3-border']) ?>
            </div>

            <div class="w3-col">
                <?= $form->field($model, 'mailing_address')->textarea(['rows' => 3, 'class' => 'w3-input w3-border']) ?>
            </div>
            
        </div>
    </fieldset>
    
    <div class="w3-row-padding w3-margin-top">
        <div class="w3-third">
            <?= Html::submitButton('Save', ['class' => 'w3-btn w3-green']) ?>
        </div>        
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/staff/views/parents/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Parents */

$this->title = 'Enrol Parent';
$this->params['breadcrumbs'][] = ['label' => 'Manage Parents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="w3-container w3-padding">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/staff/views/parents/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ParentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Parents';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="w3-container">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Enrol Parent', ['create'], ['class' => 'w3-btn w3-green w3-padding']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'tableOptions' => ['class' => 'w3-table-all'],
        'emptyCell' => '--',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'first_name',
            'middle_name',
            'last_name',            
            'phone',
            [
                'class' => 'yii\grid\ActionColumn',

                'template' => '{view} {update}',

                'buttons' => [

                    'view' => function($url, $model){
                        return Html::a('<i class="far fa-eye"></i>', ['view', 'id' => $model->id ], ['title' => 'View' ]);
                    },

                    'update' => function($url, $model){
                        return Html::a('<i class="far fa-edit"></i>', ['update', 'id' => $model->id ], ['title' => 'Update' ]);
                    }
                ]
            
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

modules/staff/views/parents/reset-user-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = "Reset Password";
$this->params['breadcrumbs'][] = ['label' => 'Manage Parents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $user->getFullName(), 'url' => ['view', 'id' => $user->id]];
$this->params['breadcrumbs'][] = 'Reset Password';

?>



<div class="w3-container w3-half">
<h1><?= $this->title ?></h1>
<h3><?= $user->getFullName() ?></h3>

    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="w3-panel w3-green w3-display-container">
        <span onclick="this.parentElement.style.display='none'"
        class="w3-button w3-large w3-display-topright">&times;</span>
        <h4><i class="glyphicon glyphicon-ok-sign"></i> &nbsp;Password Updated!</h4>
        <p><?= Yii::$app->session->getFlash('success') ?></p>
        </div>
    <?php endif; ?>

    <?php $form = ActiveForm::begin([ 'id' => 'password-reset-form','enableClientValidation' => true, ]); ?>
        
        <div class="w3-panel w3-light-grey w3-padding w3-border">
            <br>
            <p>Clicking on the <b>Reset Password</b> button below will automatically generate a new password and forward it to the user's email address</p>
            <?= Html::submitButton('Reset Password', ['class' => 'w3-btn w3-blue']) ?>
        </div>  
    
    <?php $form = ActiveForm::end() ?>

</div>

modules/staff/views/parents/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Parents */

$this->title = 'Update Parent';
$this->params['breadcrumbs'][] = ['label' => 'Manage Parents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->getFullName(), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="w3-container">

    <h1><?= Html::encode($this->title) ?></h1>
    <h3><?= $model->getFullName() ?></h3>

    <br>

    <?= $this->render('_update_form', [
        'model' => $model,
    ]) ?>

</div>

modules/staff/views/parents/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Student;
use app\models\SchoolClass;


/* @var $this yii\web\View */
/* @var $model app\models\Parents */

$this->title = $model->getFullName();
$this->params['breadcrumbs'][] = ['label' => 'Manage Parents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);


    $wards = $model->getWardsList();

?>
<div class="w3-container">

    <div class="w3-row-padding">
    
        <div class="w3-half">

            <h1><?= Html::encode($this->title) ?></h1>

            <p>
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'w3-btn w3-green w3-padding']) ?>
                <?= Html::a('Link Child/Ward To Parent', ['link-ward', 'id' => $model->id], ['class' => 'w3-btn w3-blue w3-padding']) ?>
                <?= Html::a('Reset Password', ['reset-password', 'id' => $model->id], ['class' => 'w3-btn w3-blue w3-padding']) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'options' => ['class' => 'w3-table-all'],
                'attributes' => [            
                    'first_name',
                    'middle_name',
                    'last_name',
                    'address:ntext',
                    'email:email',
                    'phone',
                    [
                        'label' => 'Phone (Alternative Number)',
                        'attribute'=>'phone2',
                        'value'=>$model->phone2,                
                    ],
                    'residence_phone',
                    'employer',
                    'office_phone',
                    'work_address:ntext',
                    'mailing_address:ntext',            
                    'last_login',
                    [
                        'label' => 'Created On',
                        'attribute'=>'created_on',
                        'value'=>date_format(date_create($model->created_on), "M d, Y")               
                    ],
                ],
            ]) ?>

        </div>

        <div class="w3-half">
            <br> <br>
            <h3 class="w3-blue w3-padding w3-margin-top">
                Children / Wards
            </h3>

            <?php if(empty($wards)): ?>
                <p>
                    No Child/Ward is currently linked to this parent.
                    Click <?= Html::a('here', ['link-ward', 'id' => $model->id], ['class' => 'w3-black w3-padding-small']) ?>  to add their wards
                </p>
            <?php endif ?>

            <ul class="w3-ul w3-card w3-white w3-margin-bottom w3-border">
                <?php foreach($wards as $ward): ?>
                    <?php $student = Student::findOne($ward->student_id) ?>
                    <li class="w3-bar">
                        <img src="<?= empty($student->picture) ? '/images/student-avatar.png' : $student->picture ?>" class="w3-bar-item w3-round w3-hide-small" style="width:85px">
                        <div class="w3-bar-item">
                            <span class="w3-large">
                                <?= Html::a($student->getFullName(), ['student/view', 'id' => $student->id]) ?>                     
                            </span><br>
                            <span>
                                <?= SchoolClass::findOne($student->current_class)->class_name ?>
                            </span>
                        </div>
                        <span class="w3-right">
                            <?= Html::a('<i class="fas fa-user-times"></i>', 
                                ['unlink-ward', 'pid' => $model->id, 'sid' => $ward->student_id], 
                                [
                                    'class' => 'w3-btn', 
                                    'title' => 'Detach',
                                    'data-confirm' => 'Confirm to detach this child from parent'
                                ]) 
                            ?>
                        </span>  
                    </li>
                <?php endforeach ?>
            </ul>
        </div>

    </div>

</div>