modules/staff/controllers/DefaultController.php
<?php

namespace app\modules\staff\controllers;

use Yii;
use yii\web\Controller;
use app\models\StaffLoginForm;
use app\models\Staff;
use app\models\Lgas;
use app\models\PasswordResetForm;
use app\models\GeneralSettings;

/**
 * Default controller for the `staff` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
    	$this->layout = false;
        

        $model = new StaffLoginForm();

        if($model->load(Yii::$app->request->post()) && $model->login())
        {
           return $this->redirect(['dashboard']);
        }

        $model->password = '';
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    public function actionPdftest()
    {
        $this->layout = false;
        return $this->render('@app/modules/staff/views/primary-report-card/primary-report-card-pdf');
    }

    public function actionTermSessionStatus()
    {
        $this->layout = '@app/views/layouts/staffLayout';

        $model = GeneralSettings::findOne(1);

        return $this->render('term-session-settings', ['currentSettings' => $model]);
    }

    public function actionConfigureTermSession()
    {
        $this->layout = '@app/views/layouts/staffLayout';

        $model = GeneralSettings::findOne(1);

        if($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect(['term-session-status']);
        }

        return $this->render('session-configuration', ['model' => $model]);
    }

    public function actionDashboard()
    {
    	$this->layout = '@app/views/layouts/staffLayout';

    	return $this->render('dashboard');
    }

    public function actionMyProfile()
    {
        $this->layout = '@app/views/layouts/staffLayout';

        $id = Yii::$app->staff->getId();
        $staff = Staff::findOne($id);        

        return $this->render('my-profile', ['model' => $staff]);
    }

    public function actionUpdateMyProfile()
    {
        $this->layout = '@app/views/layouts/staffLayout';

        $id = Yii::$app->staff->getId();

        $staff = Staff::findOne($id);
        $staff->scenario = Staff::SCENARIO_UPDATE;

        if ($staff->load(Yii::$app->request->post()) && $staff->save()) {
            return $this->redirect(['my-profile']);
        }

        return $this->render('update-my-profile', ['model' => $staff]);
    }

    public function actionChangeMyPassword()
    {
        $this->layout = '@app/views/layouts/staffLayout.php';
        $model = new PasswordResetForm();
        $staff = Staff::findOne(['id' => Yii::$app->staff->getId()]);

        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $hash = hash('sha256', $model->password);
            $staff->password = $hash;
            if($staff->save(false)) Yii::$app->session->setFlash('success', "Password reset successful!");
         
            return $this->render('change-my-password', ['model' => $model, 'user' => $staff]);

        }
        return $this->render('change-my-password', ['model' => $model, 'user' => $staff]);
    }

    public function actionLogout()
    {
        Yii::$app->staff->logout();

        return $this->redirect(['index']);
    }

    public function actionTimetable($class)
    {
        $this->layout = '@app/views/layouts/staffLayout';
        $page = '';
        $title = '';

        switch ($class) 
        {
            case 'pre-nursery':
                $page = '@app/views/timetables/pre-nursery-timetable';
                $title = "Pre-Nursery Timetable";
                break;
            
            case 'nursery1':
                $page = '@app/views/timetables/nursery-1-timetable';
                $title = "Nursery One Timetable";               
                break;
            
            case 'nursery2':
                $page = '@app/views/timetables/nursery-2-timetable';
                $title = "Nursery Two Timetable";                
                break;
            
            case 'grade1':
                $page = '@app/views/timetables/grade-1-timetable';
                $title = "Grade One Timetable";
                break;
            
            case 'grade2':
                $page = '@app/views/timetables/grade-2-timetable';
                $title = "Grade Two Timetable";
                break;

            case 'grade3':
                $page = '@app/views/timetables/grade-3-timetable';
                $title = "Grade Three Timetable";
                break;
            
            case 'grade4':
                $page = '@app/views/timetables/grade-4-timetable';
                $title = "Grade Four Timetable";
                break;
            
            case 'grade5':
                $page = '@app/views/timetables/grade-5-timetable';
                $title = "Grade Five Timetable";
                break;

            default:
                # code...
                break;
        }


        return $this->render($page, ['title' => $title]);
    }

    public function actionGetStateLgas()
    {
        //$this->enableCsrfValidation = false;
        $lgas = Lgas::find()->where(['state_id' => $_POST['id']])->all();
        $list = '';

        foreach($lgas as $lga)
        {
            $list .= "<option value='".$lga->id."'>".$lga->lga_name."</option>";
        }

        echo $list;

    }

    public function beforeAction($action)
    {            
        if ($action->id == 'get-state-lgas') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }
}

modules/staff/views/default/access-restriction-page.php
<div class="w3-container w3-center">

    <div class='w3-pale-red w3-col w3-margin-top w3-padding w3-border w3-border-red'>
        <h3>You do not have permission to view this page !!!</h3>
        <i class="fas fa-user-lock w3-xxxlarge"></i>
    </div>
</div>

modules/staff/views/default/change-my-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>



<div class="w3-container w3-half">
<h2>Change My Password</h2>
<br>
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="w3-panel w3-green w3-display-container">
        <span onclick="this.parentElement.style.display='none'"
        class="w3-button w3-large w3-display-topright">&times;</span>
        <h4><i class="glyphicon glyphicon-ok-sign"></i> &nbsp;Password Updated!</h4>
        <p><?= Yii::$app->session->getFlash('success') ?></p>
        </div>
    <?php endif; ?>

    <?php $form = ActiveForm::begin([ 'id' => 'password-reset-form','enableClientValidation' => true, ]); ?>

        
        <div class="w3-panel w3-light-grey w3-padding w3-border">
            <label for="password">Password</label>			
            <?= $form->field($model, 'password')->passwordInput(['class' => 'w3-input w3-border'])->label(false) ?>
               
            <label for="password_confirm">Confirm Password</label>
            <?= $form->field($model, 'password_confirm')->passwordInput(['class' => 'w3-input w3-border'])->label(false) ?>

            <br>
            <?= Html::submitButton('Submit', ['class' => 'w3-btn w3-blue', 'name' => 'submit']) ?>
        </div>
        
        

        
    <?php $form = ActiveForm::end() ?>

</div>

modules/staff/views/default/dashboard.php
<?php
    use yii\helpers\Html;
    use app\models\Student;
    use app\models\Parents;
    use app\models\Staff;
?>

<div class="w3-container">
    <header class="w3-container" style="padding-top:22px">
        <h1><b><i class="fa fa-dashboard"></i> ROKIS Dashboard</b></h1>
    </header>

    <div class="w3-row-padding">
        <h2 class="w3-center">Stats</h2>

        <div class="w3-quarter">
            <div class="w3-container w3-black w3-border w3-padding-16">
                <div class="w3-left"><i class="far fa-clock w3-xxxlarge"></i></div>
                <div class="w3-left w3-margin-left">
                    <h3>Today is:</h3>
                </div>
                <div class="w3-clear"></div>
                <h4> <?= date('l d F, Y') ?> </h4>
            </div>
        </div>

        <div class="w3-quarter">
            <div class="w3-container w3-red w3-padding-16">
                <div class="w3-left"><i class="fas fa-user-graduate fa-fw w3-xxxlarge"></i></div>
                <div class="w3-right">
                    <h3><?= Student::getStudentCount() ?></h3>
                </div>
                <div class="w3-clear"></div>
                <h4>No. of Students</h4>
            </div>
        </div>

        <div class="w3-quarter">
            <div class="w3-container w3-light-blue w3-padding-16">
                <div class="w3-left"><i class="fas fa-users fa-fw w3-xxxlarge"></i></div>
                <div class="w3-right">
                    <h3><?= Parents::getParentCount() ?></h3>
                </div>
                <div class="w3-clear"></div>
                <h4>No. of Parents</h4>
            </div>
        </div>

        <div class="w3-quarter">
            <div class="w3-container w3-teal w3-padding-16">
                <div class="w3-left"><i class="fas fa-chalkboard-teacher fa-fw w3-xxxlarge"></i></div>
                <div class="w3-right">
                    <h3><?= Staff::getStaffCount() ?></h3>
                </div>
                <div class="w3-clear"></div>
                <h4>No. of Staff</h4>
            </div>
        </div>
    </div>

    <div class="w3-row-padding w3-margin-top">
        <h2 class="w3-center">Quick Links</h2>
        <div class="w3-third">
            <?= Html::a("Enrol Student <i class='fas fa-plus'></i>", ['/staff/student/create'], ['class' => 'w3-button w3-block w3-white w3-border w3-border-red w3-text-red w3-round']) ?>
        </div>

        <div class="w3-third">
            <?= Html::a("Enrol Parent <i class='fas fa-plus'></i>", ['/staff/parents/create'], ['class' => 'w3-button w3-block w3-white w3-border w3-border-light-blue w3-text-light-blue w3-round']) ?>
        </div>

        <div class="w3-third">
            <?= Html::a("Enrol Staff <i class='fas fa-plus'></i>", ['/staff/manage-staff/create'], ['class' => 'w3-button w3-block w3-white w3-border w3-border-teal w3-text-teal w3-round']) ?>
        </div>
    </div>
</div>

modules/staff/views/default/index.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
?>

<!DOCTYPE html>
<html>
    <head>
        <title>Royal Kiddies Staff Portal</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/w3.css">
        <style type="text/css">
            body {
                height: 100vh;
              background: url(/images/chalk.jpg);
              background-repeat: no-repeat;
              background-size: cover;
              min-height: ;
            }
        </style>
    </head>
    <body>

        <header class="w3-container w3-blue">
          <h1>ROKIS Staff Portal</h1>
        </header>

        <div class=" w3-half w3-card-4 w3-round-large w3-margin w3-yellow">

        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'options' => ['class' => 'w3-container  ']
        ]); ?>
        

            <p>
            <?= $form->field($model, 'username')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border'])->label(false) ?>
            <label>Username</label></p>
            <p>
            <?= $form->field($model, 'password')->passwordInput(['class' => 'w3-input w3-border'])->label(false) ?>
            <label>Password</label></p>
            

            <p>
                <?= Html::submitButton('Login', ['class' => 'w3-button w3-section w3-blue w3-ripple']) ?>
            </p>

        <?php ActiveForm::end(); ?>

        </div>

    </body>
</html> 

modules/staff/views/default/my-profile.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Staff */

$this->title = 'My Profile';
$this->params['breadcrumbs'][] = ['label' => 'Staff', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="w3-container w3-half">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update-my-profile'], ['class' => 'w3-btn w3-green w3-padding']) ?>
        <?= Html::a('Change My Password', ['change-my-password'], ['class' => 'w3-btn w3-blue w3-padding']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'options' => ['class' => 'w3-table-all'],
        'attributes' => [
            'first_name',
            'middle_name',
            'last_name',
            'current_designation:ntext',
            'email:email',
            'phone',
            'last_login',
            'status',
            [
                'label' => 'Created On',
                'attribute'=>'creation_date',
                'value'=>date_format(date_create($model->creation_date), "M d, Y")               
            ],
        ],
    ]) ?>

</div>

modules/staff/views/default/session-configuration.php
<?php
    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
    use yii\jui\DatePicker;
    use yii\helpers\ArrayHelper;
    use app\models\Session;

    $this->title = "Update Configuration";
	$this->params['breadcrumbs'][] = 'System Settings';
	$this->params['breadcrumbs'][] = ['label' => 'Session Configuration', 'url' => ['default/term-session-status']];
	$this->params['breadcrumbs'][] = $this->title;

?>



<div class="w3-container w3-half">
    <h2><?= $this->title ?></h2>
    
    <?php $form = ActiveForm::begin([ 'id' => 'session-settings-configuration-form','enableClientValidation' => true, ]); ?>

        
        <div class="w3-panel w3-light-grey w3-padding w3-border">
            <div class="w3-row-padding">
                <div class="w3-half">
                    <label>Current Session</label>			
                    <?= 
                        $form->field($model, 'current_session')->dropDownList(
                        ArrayHelper::map(Session::find()->all(), 'id', 'session_title'), 
                        [ 'class' => 'w3-select w3-border' ])->label(false) 
                    ?>
                </div>

                <div class="w3-half">
                    <label>Current Term</label>
                    <?= 
                        $form->field($model, 'current_term')->dropDownList(
                        [
                            1 => '1st Term',
                            2 => '2nd Term',
                            3 => '3rd Term'
                        ], 
                        [ 'class' => 'w3-select w3-border' ])->label(false)
                    ?>
                </div>
            </div>
             
            <div class="w3-row-padding">
                <div class="w3-half">
                    <label>Term Start Date</label>
                    <?= $form->field($model, 'term_starts')->widget(DatePicker::className(),
                        ['clientOptions' => ['changeYear' => true],
                        'dateFormat' => 'y-MM-dd' ])->textInput(['class' => 'w3-input w3-border'])->label(false) 
                    ?>
                </div>
                
                <div class="w3-half">
                    <label>Term End Date</label>
                    <?= $form->field($model, 'term_ends')->widget(DatePicker::className(),
                        ['clientOptions' => ['changeYear' => true],
                        'dateFormat' => 'y-MM-dd' ])->textInput(['class' => 'w3-input w3-border'])->label(false) 
                    ?>
                </div>
            </div>
                   
            <br>
            <div class="w3-row-padding">
                <div class="w3-third">
                    <?= Html::submitButton('Submit', ['class' => 'w3-btn w3-green']) ?>
                </div>
            </div>
            
        </div>

    <?php $form = ActiveForm::end() ?>

</div>

modules/staff/views/default/term-session-settings.php
<?php
	use app\models\Session;
	use yii\helpers\Html;

	$this->title = "Current Settings";
	$this->params['breadcrumbs'][] = 'System Settings';
	$this->params['breadcrumbs'][] = ['label' => 'Session Configuration', 'url' => ['default/term-session-status']];
	
?>
<div class="w3-container w3-half">
	<h1><?= $this->title ?></h1>
	<p class="w3-border w3-border-amber w3-red w3-padding">
		!!! Ensure the DATE, TERM and SESSION are configured correctly, as this is what is used by the system for REPORT CARD preparation
	</p>
	<div class="w3-panel w3-padding w3-border w3-light-grey">
		<p>
			Current System Date is : <span class="w3-tag w3-round"> <?= date('d M, Y') ?> </span>
		</p>

		<p>
			The current system TERM is: <span class="w3-tag w3-round"> <?= Yii::$app->formatter->asOrdinal($currentSettings->current_term) . ' TERM' ?> </span> 
		</p>

		<p>
			The current system SESSION is: <span class="w3-tag w3-round"> <?= Session::findOne($currentSettings->current_session)->session_title ?> </span>
		</p>
	</div>

	<p>If parameters are incorrect, click on the <b>Configure</b> button below to update appropriate values</p>
	<?= Html::a("Configure", ['configure-term-session'], ['class' => 'w3-bar-item w3-button w3-padding w3-blue']) ?>

</div>

modules/staff/views/default/update-my-profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Staff */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Update My Profile';
?>

<div class="w3-container w3-twothird w3-padding">

    <h1><?= Html::encode($this->title) ?></h1>
    <br>

    <?php $form = ActiveForm::begin([
        'id' => 'staff-creation-form',
        'options' => ['class' => 'w3-container w3-border w3-padding w3-light-grey']
    ]); ?>

    

    <div class="w3-row-padding">
        <div class="w3-third">
           <?= $form->field($model, 'first_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?> 
        </div>

        <div class="w3-third">
            <?= $form->field($model, 'middle_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>

        <div class="w3-third">
            <?= $form->field($model, 'last_name')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>
    </div>

    <div class="w3-row-padding">
        <div class="w3-col">
            <?= $form->field($model, 'current_designation')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>
    </div>

    <div class="w3-row-padding">
        <div class="w3-half">
           <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border w3-grey', 'readonly' => 'true']) ?> 
        </div>

        <div class="w3-half">
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true, 'class' => 'w3-input w3-border']) ?>
        </div>

    </div>

    <div class="w3-row-padding">
        <div class="w3-half">
            <?= Html::submitButton('Update', ['class' => 'w3-btn w3-green']) ?>   
        </div>        
    </div>

    <?php ActiveForm::end(); ?>

</div>